In [1]:
import pandas as pd
import numpy as np

In [119]:
df_path = r'C:\animation_technique_classification\Data\Raw_Data\Raw_Data.csv'

df = pd.read_csv(df_path)

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2370 entries, 0 to 2369
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 2370 non-null   int64
 1   Title                2370 non-null   str
 2   Country              2369 non-null   str
 3   Director             2324 non-null   str
 4   Studio               2236 non-null   str
 5   Animation technique  2352 non-null   str
 6   Type                 192 non-null    str
 7   Notes                1725 non-null   str
 8   Release date         2354 non-null   str
 9   Duration             2319 non-null   str
dtypes: int64(1), str(9)
memory usage: 185.3 KB

In [121]:

df.sample(15)

,Year,Title,Country,Director,Studio,Animation technique,Type,Notes,Release date,Duration
2086,2024,Boys Go to Jupiter,United States,Julian Glander,Glanderco,CG animation,NaN,[ 27 ],"June 7, 2024 ( Tribeca ) August 8, 2025 (Unite...",90 minutes
1654,2021,Detective Conan: The Scarlet Bullet 名探偵コナン 緋色の弾丸,Japan,Tomoka Nagaoka,TMS Entertainment,Traditional,NaN,[ 93 ],"April 16, 2021",110 minutes
1362,2019,Captain Sabertooth and the Magic Diamond Kapte...,Norway Belgium,Rasmus A. Sivertsen Marit Moum Aune,Qvisten Animation,CG animation,NaN,[ 34 ] [ 35 ] [ 36 ],"September 27, 2019 [ 37 ]",81 minutes [ 37 ]
2123,2024,Gracie & Pedro: Pets To The Rescue,Canada South Africa United States,Kevin Donovan Gottfried Roodt,GTE Productions Second Chance Productions,CG animation,NaN,[ citation needed ],"May 23, 2024 (Russia) August 9, 2024 (United K...",87 minutes
1088,2017,GadgetGang in Outer Space BugiGangue no Espaço,Brazil United States India Hungary,Ale McHaddo,44 Toons! Studio56,CGI animation,NaN,[ 88 ] [ 89 ] [ 90 ],"February 23, 2017 (Brazil) July 4, 2017 (Unite...",80 minutes [ 91 ]
1235,2018,Funan [ citation needed ],France Belgium Luxembourg Cambodia,Denis Do,"Les Films d'Ici, Lunanime, Bac Films, Web Spid...",Traditional,NaN,[ 77 ],"June 11, 2018 ( Annecy International Animation...",84 minutes [ 60 ]
1264,2018,La Leyenda del Charro Negro,Mexico,Alberto Rodriguez,Ánima Estudios,Flash animation,NaN,[ 122 ],"January 19, 2018",85 minutes
1459,2019,Teen Titans Go! vs. Teen Titans,United States,Jeff Mednikow,Warner Bros. Animation DC Entertainment,Flash animation,NaN,NaN,"July 21, 2019 ( San Diego Comic-Con ) [ 192 ] ...",77 minutes
1215,2018,Coconut the Little Dragon: Into the Jungle Der...,Germany,Anthony Power,Caligari Film,CG animation,NaN,[ 42 ],"December 27, 2018 [ 21 ]",80 minutes
1099,2017,Hey Arnold!: The Jungle Movie,United States,Raymie Muzquiz Stu Livington,"Snee-Oosh, Inc. Nickelodeon Animation Studio",Traditional,NaN,NaN,"November 24, 2017",81 minutes
2213,2024,Wonderful Pretty Cure! The Movie: A Grand Adve...,Japan,Naoki Miyahara,Toei Animation,Traditional,NaN,[ 273 ],"September 13, 2024",70 minutes [ 274 ]
167,2011,The Jungle Bunch: Back to the Ice Floe Les As ...,France,David Alaux Éric Tosti,TAT Production,Computer,NaN,NaN,"December 31, 2011",58 minutes
1743,2021,Sing a Bit of Harmony アイの歌声を聴かせて,Japan,Yasuhiro Yoshiura,J.C.Staff,Traditional,NaN,[ 265 ] [ 266 ] [ 267 ],"October 29, 2021",108 minutes
1003,2016,Sinbad: Pirates of the Seven Storms,Russia,Vlad Barbe,CTB Film Company,Traditional,NaN,[1],"October 27, 2016",74 minutes
339,2012,Pretty Cure All Stars New Stage: Friends of th...,Japan,NaN,Toei Animation,Traditional,NaN,NaN,"March 17, 2012",70 minutes

In [122]:
df['Release date'] = pd.to_datetime(df['Release date'], errors='coerce')

In [123]:
df = df.dropna(subset='Release date')

In [124]:
df.info()

<class 'pandas.DataFrame'>
Index: 1417 entries, 0 to 2367
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 1417 non-null   int64
 1   Title                1417 non-null   str
 2   Country              1417 non-null   str
 3   Director             1383 non-null   str
 4   Studio               1308 non-null   str
 5   Animation technique  1402 non-null   str
 6   Type                 107 non-null    str
 7   Notes                995 non-null    str
 8   Release date         1417 non-null   datetime64[us]
 9   Duration             1386 non-null   str
dtypes: datetime64[us](1), int64(1), str(8)
memory usage: 121.8 KB

In [125]:
df['Release date']

0      2010-01-22
2      2010-03-05
3      2010-10-07
4      2014-07-10
6      2010-11-26
          ...
2362   2025-02-11
2363   2025-09-23
2364   2025-09-12
2366   2025-01-02
2367   2025-10-24
Name: Release date, Length: 1417, dtype: datetime64[us]

In [126]:
df = df.drop(['Type', 'Notes'], axis=1)

In [127]:
df.info()

<class 'pandas.DataFrame'>
Index: 1417 entries, 0 to 2367
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 1417 non-null   int64
 1   Title                1417 non-null   str
 2   Country              1417 non-null   str
 3   Director             1383 non-null   str
 4   Studio               1308 non-null   str
 5   Animation technique  1402 non-null   str
 6   Release date         1417 non-null   datetime64[us]
 7   Duration             1386 non-null   str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 99.6 KB

## Feature adding

In [128]:
df['Release Year'] = df['Release date'].dt.year
df['Release month'] = df['Release date'].dt.month
df['Release day'] = df['Release date'].dt.day

In [129]:
df['is_holiday'] = df['Release date'].dt.month.isin([11, 12])

In [131]:
df['Duration_Minutes'] = df['Duration'].str.extract('(\d+)').astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\jyusu\AppData\Local\Temp\ipykernel_21396\1532389331.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Duration_Minutes'] = df['Duration'].str.extract('(\d+)').astype(float)

In [132]:
df

,Year,Title,Country,Director,Studio,Animation technique,Release date,Duration,Release Year,Release month,Release day,is_holiday,Duration_Minutes
0,2010,"AAA - The Movie AAA, la película: Sin límite e...",Mexico,Alberto Rodriguez,Promociones Antonio Peña Ánima Estudios,Flash animation,2010-01-22,96 minutes,2010,1,22,False,96.0
2,2010,Alice in Wonderland (2010 film),United States,Tim Burton,Walt Disney Pictures Roth Films The Zanuck Com...,CGI/Live-Action,2010-03-05,108 minutes,2010,3,5,False,108.0
3,2010,Animals United Konferenz der Tiere,Germany,"Reinhard Klooss, Holger Tappe",Constantin Film,CG animation,2010-10-07,93 minutes,2010,10,7,False,93.0
4,2010,Anpanman: Blacknose and the Magical Song ja:それ...,Japan,Jun Kawagoe,"Anpanman Production Committee, TMS Entertainment",Traditional,2014-07-10,52 minutes,2014,7,10,False,52.0
6,2010,Las aventuras de Don Quijote,Spain,Antonio Zurera,NaN,Traditional / CG animation,2010-11-26,73 minutes,2010,11,26,True,73.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2362,2025,The Witcher: Sirens of the Deep,United States South Korea Poland,Kang Hei Chul,Netflix Studio Mir Platige Image Hivemind,Traditional,2025-02-11,91 minutes,2025,2,11,False,91.0
2363,2025,Yooz,Iran,Reza Arzangi,Soure Cinema Development Organization,CG animation,2025-09-23,90 minutes,2025,9,23,False,90.0
2364,2025,You and Idol Pretty Cure the Movie: For You! O...,Japan,Kōji Ogawa,Toei Animation,Traditional,2025-09-12,71 minutes [ 376 ],2025,9,12,False,71.0
2366,2025,Zanna: Whisper of Volcano Isle,Indonesia,Larry Whitaker,MNC Pictures MNC Animation,CG animation,2025-01-02,94 minutes,2025,1,2,False,94.0
2367,2025,Zombie Land Saga: Yumeginga Paradise,Japan,Kōnosuke Uda [ a ] Takafumi Ushida Takeru Satō,MAPPA,Traditional,2025-10-24,122 minutes [ 384 ],2025,10,24,False,122.0

In [136]:
df['movie_category'] = pd.cut(df['Duration_Minutes'],
                               bins=[0, 45, 90, 150, 200],
                              labels=['short', 'standart', 'long', 'epic'])

In [138]:
df.sample(5)

,Year,Title,Country,Director,Studio,Animation technique,Release date,Duration,Release Year,Release month,Release day,is_holiday,Duration_Minutes,movie_category
177,2011,Leapfrog: Phonics Farm,United States,Ron Myrick,Chris D'Angelo Productions LeapFrog Lionsgate,Traditional,2011-11-08,38 minutes,2011,11,8,True,38.0,short
1688,2021,Justice Society: World War II,United States,Jeff Wamester,Warner Bros. Animation DC Entertainment,Traditional,2021-04-27,84 minutes,2021,4,27,False,84.0,standart
1581,2020,Revue Starlight Rondo Rondo Rondo,Japan,Tomohiro Furukawa,Kinema Citrus,Traditional,2020-08-07,119 minutes,2020,8,7,False,119.0,long
2336,2025,The Quest Csongor és Tünde,Hungary,Csaba Máli Zsolt Pálfi,Cinemon Entertainment,Traditional,2025-04-17,82 minutes,2025,4,17,False,82.0,standart
676,2014,Tale of the Rally,China,Zheng Chongxin,NaN,Traditional,2014-09-06,82 minutes,2014,9,6,False,82.0,standart

In [139]:
df = df.drop(columns=['Year', 'Release date', 'Duration'])

In [140]:
df.sample(5)

,Title,Country,Director,Studio,Animation technique,Release Year,Release month,Release day,is_holiday,Duration_Minutes,movie_category
1155,Si Juki the Movie,Indonesia,Faza Meonk,Falcon Pictures,Traditional,2017,12,28,True,110.0,long
1736,Scooby-Doo! The Sword and the Scoob,United States,Maxwell Atoms Mel Zwyer Christina Sotta,Warner Bros. Animation,Traditional,2021,2,23,False,76.0,standart
1568,Oresuki: Game Over,Japan,Noriaki Akitaya,Connect,Traditional,2020,9,2,False,70.0,standart
1265,Liz and the Blue Bird Rizu to Aoi tori,Japan,Naoko Yamada,Kyoto Animation,Traditional,2018,4,21,False,90.0,standart
1797,Detective Conan: The Bride of Halloween,Japan,Susumu Mitsunaka,TMS Entertainment,Traditional,2022,4,15,False,111.0,long